config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
  }
  devise_for :shops, controllers: {
    sessions: 'shop/sessions',
    registrations: 'shop/registrations',
    passwords: 'shop/passwords',
  }
  devise_for :customers, controllers: {
    sessions: 'public/sessions',
    registrations: 'public/registrations',
    passwords: 'public/passwords',
  }
  scope module: :admin do
    resources :genres, only: [:index, :create, :edit, :update]
  end

  scope module: :public do
    root 'homes#top'
    get 'about', to: 'homes#about'
    get 'customers/mypage' => 'customers#mypage', as: 'mypage'
    get 'customers/information/edit' => 'customers#edit', as: 'edit_information'
    patch 'customers/information' => 'customers#update', as: 'update_information'
    put 'customers/information' => 'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'confirm_unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw_customer'
    put 'customers/withdraw' => 'customers#withdraw'
    get 'reserves/confirm', to: 'reserves#confirm', as: 'reserve_confirm'
    post 'reserves/confirm', to: 'reserves#confirm', as: 'reserves_confirm_post'
    post 'reserves/create', to: 'reserves#create', as: 'reserves_create'
    get 'reserves/done', to: 'reserves#done', as: 'reserves_done'
    get 'customers/:customer_id/talk_rooms/:id' => 'talks#show', as: 'customers_talk'
    get 'customers/talks' => 'talks#index', as: 'customers_talks'
    get 'search', to: 'searchs#search', as: 'search'
    get 'map_search', to: 'searchs#map_search', as: 'map_search'
    get 'customers/follows' => 'relationships#follow', as: 'follow'
    get 'customers/bookmarks' => 'bookmarks#index', as: 'bookmarks'
    get 'customers/reserve' => 'reserves#new', as: 'reserve'
    get 'customers/rank' => 'customers#rank', as: 'customers_rank'
    get 'imgsearch', to: 'img_searchs#search', as: 'img_search'

    resources :customers, only: [:index, :show] do
      resources :talks, only: [:create]
      resource :relationships, only: [:create, :destroy]
      resources :reservation_menus, only: [:create]
      resources :reservation_histories, only: [:index] do
        resources :history_comments, only: [:create, :destroy]
      end
    end
    resources :reservation_menus, only: [:index]
    resources :talks, only: [:create]
    resources :img_searchs, only: [:create, :new]
    delete 'img_searchs/:id' => 'img_searchs#destroy', as: 'img_search_destroy'
  end

  scope module: :shop do
    get 'shops/mypage' => 'shops#mypage', as: 'shop_mypage'
    get 'shops/information/edit' => 'shops#edit', as: 'edit_shop_information'
    patch 'shops/information' => 'shops#update', as: 'update_shop_information'
    put 'shops/information' => 'shops#update'
    get 'shops/unsubscribe' => 'shops#unsubscribe', as: 'confirm_shop_unsubscribe'
    patch 'shops/withdraw' => 'shops#withdraw', as: 'withdraw_shop'
    put 'shops/withdraw' => 'shops#withdraw'
    get 'shops/:id/menulist' => 'shops#menu', as: 'shop_menu_list'
    get 'posts/all' => 'posts#all_index'
    get 'posts/rank' => 'posts#rank'
    get 'shops/:id/postlist' => 'posts#list', as: 'shop_posts_list'
    get 'shops/map' => 'shops#map', as: 'shops_map'
    get 'talk_rooms/:id/:shop_id/:customer_id' => 'talks#show', as: 'shops_talk'
    get 'shops/talks' => 'talks#index', as: 'shops_talks'
    get 'shops/reservation_histories' => 'reservation_histories#index', as: 'shops_histories'
    patch 'shops/reservation_histories/:id' => 'reservation_histories#update', as: 'update_history'
    get '/genres/:genre_id' => 'shops#search', as: 'shops_search'
    get '/mapgenres/:genre_id' => 'shops#map_search', as: 'shops_map_search'
    get 'shops/:id/review' => 'reservation_histories#review', as: 'shop_review'

    resources :shops, only: [:index, :show] do
      resources :menus, except: [:show]
      resource :bookmarks, only: [:create, :destroy]
      resources :talks, only: [:create]
      resources :posts do
        resources :post_comments, only: [:create, :destroy]
        resource :favorites, only: [:create, :destroy]
      end
    end
  end
end

app/controllers/shop/bookmarks_controller.rb
class Shop::BookmarksController < ApplicationController
  before_action :authenticate_customer!

  def create
    @shop = Shop.find(params[:shop_id])
    @shops = Shop.page(params[:page]).per(20)
    @genres = Genre.page(params[:page]).per(20)
    bookmark = @shop.bookmarks.new(customer_id: current_customer.id)
    if bookmark.save
    else
      redirect_to request.referer
    end
  end

  def destroy
    @shop = Shop.find(params[:shop_id])
    @shops = Shop.page(params[:page]).per(20)
    @genres = Genre.page(params[:page]).per(20)
    bookmark = @shop.bookmarks.find_by(customer_id: current_customer.id)
    if bookmark.destroy
    else
      redirect_to request.referer
    end
  end
end

app/controllers/shop/confirmations_controller.rb
# frozen_string_literal: true

class Shop::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/shop/favorites_controller.rb
class Shop::FavoritesController < ApplicationController
  before_action :authenticate_customer!

  def create
    @post = Post.find(params[:post_id])
    @shop = @post.shop.id
    favorite = @post.favorites.new(customer_id: current_customer.id)
    if favorite.save
    else
      redirect_to request.referer
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @shop = @post.shop.id
    favorite = @post.favorites.find_by(customer_id: current_customer.id)
    if favorite.destroy
    else
      redirect_to request.referer
    end
  end
end

app/controllers/shop/menus_controller.rb
class Shop::MenusController < ApplicationController
  before_action :authenticate_shop!
  before_action :ensure_menu, only: [:edit, :update, :destroy]

  def index
    @menus = current_shop.menus.page(params[:page]).per(5)
  end

  def new
    @menu = Menu.new
  end

  def create
    @menu = Menu.new(menu_params)
    @menu.shop_id = current_shop.id
    if @menu.save
      redirect_to shop_menus_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @menu.update(menu_params)
      redirect_to shop_menus_path
    else
      render :edit
    end
  end

  def destroy
    if @menu.destroy
      redirect_to request.referer
    else
      render :edit
    end
  end

  private

  def ensure_menu
    @menus = current_shop.menus
    @menu = @menus.find_by(id: params[:id])
    unless @menu
      redirect_to shop_menus_path(current_shop)
    end
  end

  def menu_params
    params.require(:menu).permit(:name,
                                 :detail,
                                 :price,
                                 :menu_image)
  end
end

app/controllers/shop/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Shop::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/shop/passwords_controller.rb
# frozen_string_literal: true

class Shop::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/shop/post_comments_controller.rb
class Shop::PostCommentsController < ApplicationController
  before_action :authenticate_customer!

  def create
    @post = Post.find(params[:post_id])
    @shop = Shop.find(params[:shop_id])
    @post_comment = @post.post_comments.new(post_comment_params)
    @post_comment.customer_id = current_customer.id
    if @post_comment.save
    else
      @post_comment = Post.new
      @post_comments = @post.post_comments
      redirect_to request.referer
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @shop = Shop.find(params[:shop_id])
    @post_comment = PostComment.find(params[:id])
    if @post_comment.customer == current_customer
      if @post_comment.destroy
      else
        @post_comment = Post.new
        @post_comments = @post.post_comments
        redirect_to request.referer
      end
    end
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:body)
  end
end

app/controllers/shop/posts_controller.rb
class Shop::PostsController < ApplicationController
  before_action :authenticate_shop!, except: [:all_index, :rank, :show, :list]
  before_action :ensure_post, only: [:edit, :update, :destroy]

  def all_index
    @posts = Post.page(params[:page]).reverse_order.per(30)
    @tags = Tag.select(:name).distinct
  end

  def rank
    @posts = Kaminari.paginate_array(
      Post.find(
        Favorite.group(:post_id).
                order('count(post_id) desc').
                pluck(:post_id)
      )
    ).
      page(params[:page]).per(30)
  end

  def show
    @post = Post.find(params[:id])
    @shop = Shop.find(params[:shop_id])
    @post_comment = PostComment.new
    @post_comments = @post.post_comments
  end

  def list
    @shop = Shop.find(params[:id])
    @posts = @shop.posts.page(params[:page]).reverse_order.per(9)
  end

  def index
    @posts = current_shop.posts.page(params[:page]).reverse_order.per(9)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.shop_id = current_shop.id
    if @post.save
      if @post.post_image_id.present?
        tags = Vision.get_image_data(@post.post_image)
        tags.each do |tag|
          @post.tags.create(name: tag)
        end
      end
      redirect_to shop_posts_path
    else
      render :new
    end
  end

  def destroy
    if @post.destroy
      redirect_to request.referer
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      @post.tags.destroy_all
      tags = Vision.get_image_data(@post.post_image)
      tags.each do |tag|
        @post.tags.create(name: tag)
      end
      redirect_to shop_posts_path
    else
      render :edit
    end
  end

  private

  def ensure_post
    @posts = current_shop.posts
    @post = @posts.find_by(id: params[:id])
    unless @post
      redirect_to shop_posts_path(current_shop)
    end
  end

  def post_params
    params.require(:post).permit(:body, :post_image)
  end
end

app/controllers/shop/registrations_controller.rb
# frozen_string_literal: true

class Shop::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone_number, :postal_code, :prefecture_code, :city, :street, :other_address, :traffic_method, :business_hours, :budget, :payment_method, :seat, :staff, :parking, :promotion, :introduction, :shop_image, :genre_id])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    shop_mypage_path
  end

  def after_update_path_for(resource)
    shop_mypage_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/shop/reservation_histories_controller.rb
class Shop::ReservationHistoriesController < ApplicationController
  before_action :authenticate_shop!, except: [:review]
  require 'csv'

  def review
    @shop = Shop.find(params[:id])
    @menus = @shop.menus.all
    @reservation_histories = ReservationHistory.where(menu_id: @menus)
    @history_comments = HistoryComment.where(reservation_history_id: @reservation_histories).
      reverse_order
  end

  def index
    @menus = Menu.where(shop_id: current_shop)
    @reservation_histories = ReservationHistory.where(menu_id: @menus).
      includes(:reserve).
      order("reserves.reservation DESC")
    @history_comments = HistoryComment.where(reservation_history_id: @reservation_histories).
      reverse_order
    respond_to do |format|
      format.html
      format.csv do |csv|
        send_reservation_histories_csv(@reservation_histories)
      end
    end
  end

  def update
    @menus = Menu.where(shop_id: current_shop)
    @reservation_histories = ReservationHistory.where(menu_id: @menus)
    @reservation_history = @reservation_histories.find_by(id: params[:id])
    if @reservation_history.present?
      @reservation_history.update(reservation_history_params)
      redirect_to request.referer
    else
      redirect_to shops_histories_path
    end
  end

  private

  def reservation_history_params
    params.require(:reservation_history).permit(:status)
  end

  def send_reservation_histories_csv(reservation_histories)
    csv_data = CSV.generate do |csv|
      column_names = %w(予約日時 予約者 予約メニュー メニュー金額 来店状況)
      csv << column_names

      reservation_histories.each do |history|
        column_values = [
          history.reserve.reservation.to_s(:datetime_jp),
          history.reserve.customer.full_name,
          history.menu.name,
          history.menu.price.to_s(:delimited),
          history.status_i18n,
        ]
        csv << column_values
      end
    end
    send_data(csv_data, filename: "予約状況.csv")
  end
end

app/controllers/shop/sessions_controller.rb
# frozen_string_literal: true

class Shop::SessionsController < Devise::SessionsController
  before_action :reject_inactive_shop, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_in_path_for(resource)
    shop_mypage_path
  end

  def after_sign_out_path_for(resource)
    new_shop_session_path
  end

  def reject_inactive_shop
    @shop = Shop.find_by(email: params[:shop][:email])
    if @shop
      if @shop.valid_password?(params[:shop][:password]) && !@shop.is_active
        flash[:danger] = 'お客様は退会済みです。申し訳ございませんが、別のメールアドレスをお使いください。'
        redirect_to new_shop_session_path
      end
    end
  end
end

app/controllers/shop/unlocks_controller.rb
# frozen_string_literal: true

class Shop::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/shop/bookmarks_helper.rb
module Shop::BookmarksHelper
end

app/helpers/shop/favorites_helper.rb
module Shop::FavoritesHelper
end

app/helpers/shop/menus_helper.rb
module Shop::MenusHelper
end

app/helpers/shop/post_comments_helper.rb
module Shop::PostCommentsHelper
end

app/helpers/shop/posts_helper.rb
module Shop::PostsHelper
end

app/views/shop/shops/_index_form.html.erb
<div class="col-md-2">
	<table class="table table-bordered">
		<tbody>
			<tr>
				<td class="table_item_color">ジャンル検索</td>
			</tr>
			<% @genres.each do |genre| %>
				<tr>
					<td>
						<%= link_to shops_search_path(genre_id: genre.id) do %>
							<%= genre.name %>
						<% end %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>
<div class="col-md-10">
	<table class="table">
		<tbody>
			<% shops.each do |shop| %>
				<tr>
					<td>
						<div class="col-md-2">
						<%= link_to shop_path(shop) do %>
			      	<%= attachment_image_tag shop, :shop_image, format: "jpeg", fallback: "no-image.png", class: "default_image" %>
			      <% end %>
			    </div>
			    </td>
					<td>
							<h3 class="col-md-8 text-left">
								<%= link_to shop_path(shop) do %>
									<%= shop.name %>
								<% end %>
							</h3>
							<h3 class="col-md-2">
								<% if customer_signed_in? %>
									<span>
										<%= render 'shop/bookmarks/form', shop: shop %>
									</span>
								<% elsif shop_signed_in? %>
									<span>　</span>
								<% else %>
									<%= link_to new_customer_session_path do %>
										<span class="glyphicon glyphicon-star-empty"></span>
									<% end %>
								<% end %>
							</h3>
							<div class="col-md-9">
								<h4><%= shop.promotion %></h4><br>
								<span><%= shop.full_address %></span>
							</div>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/shop/shops/menu.html.erb
<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<h2>
			<%= link_to shop_path(@shop) do %>
				<%= @shop.name %>
			<% end %>
			<span class="sub_title">　のメニュー　　　<%= paginate @menus %></span>
		</h2>
		<table class="table">
			<tbody>
				<% @menus.each do |menu| %>
				<tr>
					<td><%= attachment_image_tag menu, :menu_image, format: "jpeg", fallback: "no-image.png", class: "shop_menu_image" %></td>
					<td>
						<span class="menu_name"><%= menu.name %></span><br><br>
						【<%= menu.detail %>】
					</td>
					<td><%= menu.price.to_s(:delimited) %>円</td>
					<td>
						<% if customer_signed_in? %>
							<%= form_for(@reservation_menu, url: customer_reservation_menus_path(current_customer), method: :post) do |f| %>
								<%= f.hidden_field :menu_id, :value => menu.id %>
								<%= f.hidden_field :reservation_shop, :value => menu.shop %>
								<%= f.submit '予約', class: "btn btn-primary" %>
							<% end %>
						<% else %>
							<%= link_to "予約", new_customer_session_path, class: "btn btn-primary" %>
						<% end %>
					</td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/shop/shops/show.html.erb
<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<h2 class="col-md-11">
			<%= @shop.name %>
			<%= link_to 'レビューを見る', shop_review_path, class: "btn btn-default nav-btn" %>
		</h2>
		<h2 class="col-md-1">
			<% if customer_signed_in? %>
				<span id="show_bookmark"><%= render partial: 'shop/bookmarks/form', locals: { shop: @shop } %></span>
			<% elsif shop_signed_in? %>
				<span>　</span>
			<% else %>
				<%= link_to new_customer_session_path do %>
					<span class="glyphicon glyphicon-star-empty"></span>
				<% end %>
			<% end %>
		</h2>
		<table class="table">
			<tbody>
				<tr>
					<td>
		        <%= attachment_image_tag @shop, :shop_image, format: "jpeg", fallback: "no-image.png", class: "shop_show_top_image" %>
		      </td>
					<td>
						<h3><%= @shop.promotion %></h3><br><br>
						<%= @shop.introduction %><br><br>
						<h4>おすすめジャンル　<span class="genre_box"><%= @shop.genre.name %></span></h4>
					</td>
				</tr>
			</tbody>
		</table>
	</div>
</div>
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<h3>メニュー　　　<span class="sub_title"><%= link_to 'もっと見る>', shop_menu_list_path(@shop) %></span></h4>
		<table class="table">
			<tbody>
				<% @menus.each do |menu| %>
				<tr>
					<td><%= attachment_image_tag menu, :menu_image, format: "jpeg", fallback: "no-image.png", class: "shop_menu_image" %></td>
					<td>
						<span class="menu_name"><%= menu.name %></span><br><br>
						【<%= menu.detail %>】
					</td>
					<td><%= menu.price.to_s(:delimited) %>円</td>
					<td>
						<% if customer_signed_in? %>
							<%= form_for(@reservation_menu, url: customer_reservation_menus_path(current_customer), method: :post) do |f| %>
								<%= f.hidden_field :menu_id, :value => menu.id %>
								<%= f.hidden_field :reservation_shop, :value => menu.shop %>
								<%= f.submit '予約', class: "btn btn-primary" %>
							<% end %>
						<% else %>
							<%= link_to "予約", new_customer_session_path, class: "btn btn-primary" %>
						<% end %>
					</td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<h3>最近の投稿　　<span class="sub_title"><%= link_to 'もっと見る>', shop_posts_list_path(@shop) %></span></h4>
		<% @posts.each do |post| %>
			<div class="col-md-4 col-xs-4">
				<div class="posts">
					<%= link_to shop_post_path(@shop, post) do %>
						<%= attachment_image_tag post, :post_image, format: "jpeg", fallback: "no-image.png", class: "post_default_image" %><br>
						<div class="mask">
							<div class="caption">
								<% if post.favorited_by?(current_customer) %>
									<span class="glyphicon glyphicon-heart"> <%= post.favorites.count%>　</span>
								<% else %>
									<span class="glyphicon glyphicon-heart-empty"> <%= post.favorites.count %>　</span>
								<% end %>
								<span class="glyphicon glyphicon-envelope"> <%= post.post_comments.count %></span>
							</div>
						</div>
					<% end %>
				</div>
				<div class="col-xs-offset-1" style="width: 210px; word-wrap: break-word; white-space: pre-line;">
					<%= post.body %>
				</div>
			</div>
		<% end %>
	</div>
</div>
<div class="row" style="margin-top: 30px;">
	<div class="col-md-8 col-md-offset-2">
		<table class="table table-bordered">
			<tbody>
				<tr>
					<td class="table_item_color">店舗名</td>
					<td><%= @shop.name %></td>
				</tr>
				<tr>
					<td class="table_item_color">お問い合わせ</td>
					<td><%= @shop.phone_number %></td>
				</tr>
				<tr>
					<td class="table_item_color">住所</td>
					<td>
						<%= @shop.full_address %>
						<div id='map' class="<%= @shop.prefecture_code + @shop.city + @shop.street %>"></div>
					</td>
				</tr>
				<tr>
					<td class="table_item_color">交通手段</td>
					<td style="white-space: pre-wrap;"><%= @shop.traffic_method %></td>
				</tr>
				<tr>
					<td class="table_item_color">営業時間</td>
					<td style="white-space: pre-wrap;"><%= @shop.business_hours %></td>
				</tr>
				<tr>
					<td class="table_item_color">予算</td>
					<td><%= @shop.budget.to_s(:delimited) %>円</td>
				</tr>
				<tr>
					<td class="table_item_color">お支払い方法</td>
					<td style="white-space: pre-wrap;"><%= @shop.payment_method %></td>
				</tr>
				<tr>
					<td class="table_item_color">席数</td>
					<td><%= @shop.seat %>席</td>
				</tr>
				<tr>
					<td class="table_item_color">スタッフ数</td>
					<td><%= @shop.staff %>人</td>
				</tr>
				<tr>
					<td class="table_item_color">駐車場</td>
					<td style="white-space: pre-wrap;"><%= @shop.parking %></td>
				</tr>
			</tbody>
		</table>
	</div>
</div>


<style>
#map{
  height: 200px;
}
</style>

<script>
/*
mapを関数の外で定義(codeAddressでも使うため)
geocoderを用意
*/

let map
let geocoder

function initMap(){
  // geocoderを初期化
  geocoder = new google.maps.Geocoder()
  geocoder.geocode( { 'address': $('#map').attr('class')}, function(results, status) {
    if (status == 'OK') {
　　　　　　　　　　　　// map.setCenterで地図が移動
      map.setCenter(results[0].geometry.location);

　　　　　　　　　　　　// google.maps.MarkerでGoogleMap上の指定位置にマーカが立つ
      var marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
      });
    } else {
      alert('Geocode was not successful for the following reason: ' + status);
    }
  });

  map = new google.maps.Map(document.getElementById('map'), {
  center: {lat: 34.7024, lng: 135.4959},
  zoom: 14
  });
}

function codeAddress(){
  // 入力を取得
  let inputAddress = document.getElementById('address').value;

  // geocodingしたあとmapを移動
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['SECRET_KEY'] %>&callback=initMap" async defer></script>

app/views/shop/shops/unsubscribe.html.erb
<div class="unsubscribe" >
	<h3 class="unsubscribe-head">本当に退会しますか？</h3>

	<div class="unsubscribe-text">
		<p>退会すると、会員登録情報や</p>
		<p>これまでの購入履歴が閲覧できなくなります。</p>
		<p>退会する場合は、『退会する』をクリックしてください。</p>
	</div>

	<div class="unsubscribe-bottom">
		<%= link_to '退会しない', shop_mypage_path, class: "btn btn-primary", style: "margin-right: 50px;" %>
		<%= link_to "退会する", withdraw_shop_path, method: :patch, class: "btn btn-danger" %>
	</div>
</div>