config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
  }
  devise_for :shops, controllers: {
    sessions: 'shop/sessions',
    registrations: 'shop/registrations',
    passwords: 'shop/passwords',
  }
  devise_for :customers, controllers: {
    sessions: 'public/sessions',
    registrations: 'public/registrations',
    passwords: 'public/passwords',
  }
  scope module: :admin do
    resources :genres, only: [:index, :create, :edit, :update]
  end

  scope module: :public do
    root 'homes#top'
    get 'about', to: 'homes#about'
    get 'customers/mypage' => 'customers#mypage', as: 'mypage'
    get 'customers/information/edit' => 'customers#edit', as: 'edit_information'
    patch 'customers/information' => 'customers#update', as: 'update_information'
    put 'customers/information' => 'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'confirm_unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw_customer'
    put 'customers/withdraw' => 'customers#withdraw'
    get 'reserves/confirm', to: 'reserves#confirm', as: 'reserve_confirm'
    post 'reserves/confirm', to: 'reserves#confirm', as: 'reserves_confirm_post'
    post 'reserves/create', to: 'reserves#create', as: 'reserves_create'
    get 'reserves/done', to: 'reserves#done', as: 'reserves_done'
    get 'customers/:customer_id/talk_rooms/:id' => 'talks#show', as: 'customers_talk'
    get 'customers/talks' => 'talks#index', as: 'customers_talks'
    get 'search', to: 'searchs#search', as: 'search'
    get 'map_search', to: 'searchs#map_search', as: 'map_search'
    get 'customers/follows' => 'relationships#follow', as: 'follow'
    get 'customers/bookmarks' => 'bookmarks#index', as: 'bookmarks'
    get 'customers/reserve' => 'reserves#new', as: 'reserve'
    get 'customers/rank' => 'customers#rank', as: 'customers_rank'
    get 'imgsearch', to: 'img_searchs#search', as: 'img_search'

    resources :customers, only: [:index, :show] do
      resources :talks, only: [:create]
      resource :relationships, only: [:create, :destroy]
      resources :reservation_menus, only: [:create]
      resources :reservation_histories, only: [:index] do
        resources :history_comments, only: [:create, :destroy]
      end
    end
    resources :reservation_menus, only: [:index]
    resources :talks, only: [:create]
    resources :img_searchs, only: [:create, :new]
    delete 'img_searchs/:id' => 'img_searchs#destroy', as: 'img_search_destroy'
  end

  scope module: :shop do
    get 'shops/mypage' => 'shops#mypage', as: 'shop_mypage'
    get 'shops/information/edit' => 'shops#edit', as: 'edit_shop_information'
    patch 'shops/information' => 'shops#update', as: 'update_shop_information'
    put 'shops/information' => 'shops#update'
    get 'shops/unsubscribe' => 'shops#unsubscribe', as: 'confirm_shop_unsubscribe'
    patch 'shops/withdraw' => 'shops#withdraw', as: 'withdraw_shop'
    put 'shops/withdraw' => 'shops#withdraw'
    get 'shops/:id/menulist' => 'shops#menu', as: 'shop_menu_list'
    get 'posts/all' => 'posts#all_index'
    get 'posts/rank' => 'posts#rank'
    get 'shops/:id/postlist' => 'posts#list', as: 'shop_posts_list'
    get 'shops/map' => 'shops#map', as: 'shops_map'
    get 'talk_rooms/:id/:shop_id/:customer_id' => 'talks#show', as: 'shops_talk'
    get 'shops/talks' => 'talks#index', as: 'shops_talks'
    get 'shops/reservation_histories' => 'reservation_histories#index', as: 'shops_histories'
    patch 'shops/reservation_histories/:id' => 'reservation_histories#update', as: 'update_history'
    get '/genres/:genre_id' => 'shops#search', as: 'shops_search'
    get '/mapgenres/:genre_id' => 'shops#map_search', as: 'shops_map_search'
    get 'shops/:id/review' => 'reservation_histories#review', as: 'shop_review'

    resources :shops, only: [:index, :show] do
      resources :menus, except: [:show]
      resource :bookmarks, only: [:create, :destroy]
      resources :talks, only: [:create]
      resources :posts do
        resources :post_comments, only: [:create, :destroy]
        resource :favorites, only: [:create, :destroy]
      end
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :shop

  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :tags, dependent: :destroy

  validates :body, length: {maximum: 140}

  attachment :post_image

  def favorited_by?(customer)
    favorites.where(customer_id: customer).exists?
  end
end

app/controllers/shop/bookmarks_controller.rb
class Shop::BookmarksController < ApplicationController
  before_action :authenticate_customer!

  def create
    @shop = Shop.find(params[:shop_id])
    @shops = Shop.page(params[:page]).per(20)
    @genres = Genre.page(params[:page]).per(20)
    bookmark = @shop.bookmarks.new(customer_id: current_customer.id)
    if bookmark.save
    else
      redirect_to request.referer
    end
  end

  def destroy
    @shop = Shop.find(params[:shop_id])
    @shops = Shop.page(params[:page]).per(20)
    @genres = Genre.page(params[:page]).per(20)
    bookmark = @shop.bookmarks.find_by(customer_id: current_customer.id)
    if bookmark.destroy
    else
      redirect_to request.referer
    end
  end
end

app/controllers/shop/confirmations_controller.rb
# frozen_string_literal: true

class Shop::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/shop/favorites_controller.rb
class Shop::FavoritesController < ApplicationController
  before_action :authenticate_customer!

  def create
    @post = Post.find(params[:post_id])
    @shop = @post.shop.id
    favorite = @post.favorites.new(customer_id: current_customer.id)
    if favorite.save
    else
      redirect_to request.referer
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @shop = @post.shop.id
    favorite = @post.favorites.find_by(customer_id: current_customer.id)
    if favorite.destroy
    else
      redirect_to request.referer
    end
  end
end

app/controllers/shop/menus_controller.rb
class Shop::MenusController < ApplicationController
  before_action :authenticate_shop!
  before_action :ensure_menu, only: [:edit, :update, :destroy]

  def index
    @menus = current_shop.menus.page(params[:page]).per(5)
  end

  def new
    @menu = Menu.new
  end

  def create
    @menu = Menu.new(menu_params)
    @menu.shop_id = current_shop.id
    if @menu.save
      redirect_to shop_menus_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @menu.update(menu_params)
      redirect_to shop_menus_path
    else
      render :edit
    end
  end

  def destroy
    if @menu.destroy
      redirect_to request.referer
    else
      render :edit
    end
  end

  private

  def ensure_menu
    @menus = current_shop.menus
    @menu = @menus.find_by(id: params[:id])
    unless @menu
      redirect_to shop_menus_path(current_shop)
    end
  end

  def menu_params
    params.require(:menu).permit(:name,
                                 :detail,
                                 :price,
                                 :menu_image)
  end
end

app/controllers/shop/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Shop::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/shop/passwords_controller.rb
# frozen_string_literal: true

class Shop::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/shop/post_comments_controller.rb
class Shop::PostCommentsController < ApplicationController
  before_action :authenticate_customer!

  def create
    @post = Post.find(params[:post_id])
    @shop = Shop.find(params[:shop_id])
    @post_comment = @post.post_comments.new(post_comment_params)
    @post_comment.customer_id = current_customer.id
    if @post_comment.save
    else
      @post_comment = Post.new
      @post_comments = @post.post_comments
      redirect_to request.referer
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @shop = Shop.find(params[:shop_id])
    @post_comment = PostComment.find(params[:id])
    if @post_comment.customer == current_customer
      if @post_comment.destroy
      else
        @post_comment = Post.new
        @post_comments = @post.post_comments
        redirect_to request.referer
      end
    end
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:body)
  end
end

app/controllers/shop/posts_controller.rb
class Shop::PostsController < ApplicationController
  before_action :authenticate_shop!, except: [:all_index, :rank, :show, :list]
  before_action :ensure_post, only: [:edit, :update, :destroy]

  def all_index
    @posts = Post.page(params[:page]).reverse_order.per(30)
    @tags = Tag.select(:name).distinct
  end

  def rank
    @posts = Kaminari.paginate_array(
      Post.find(
        Favorite.group(:post_id).
                order('count(post_id) desc').
                pluck(:post_id)
      )
    ).
      page(params[:page]).per(30)
  end

  def show
    @post = Post.find(params[:id])
    @shop = Shop.find(params[:shop_id])
    @post_comment = PostComment.new
    @post_comments = @post.post_comments
  end

  def list
    @shop = Shop.find(params[:id])
    @posts = @shop.posts.page(params[:page]).reverse_order.per(9)
  end

  def index
    @posts = current_shop.posts.page(params[:page]).reverse_order.per(9)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.shop_id = current_shop.id
    if @post.save
      if @post.post_image_id.present?
        tags = Vision.get_image_data(@post.post_image)
        tags.each do |tag|
          @post.tags.create(name: tag)
        end
      end
      redirect_to shop_posts_path
    else
      render :new
    end
  end

  def destroy
    if @post.destroy
      redirect_to request.referer
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      @post.tags.destroy_all
      tags = Vision.get_image_data(@post.post_image)
      tags.each do |tag|
        @post.tags.create(name: tag)
      end
      redirect_to shop_posts_path
    else
      render :edit
    end
  end

  private

  def ensure_post
    @posts = current_shop.posts
    @post = @posts.find_by(id: params[:id])
    unless @post
      redirect_to shop_posts_path(current_shop)
    end
  end

  def post_params
    params.require(:post).permit(:body, :post_image)
  end
end

app/controllers/shop/registrations_controller.rb
# frozen_string_literal: true

class Shop::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone_number, :postal_code, :prefecture_code, :city, :street, :other_address, :traffic_method, :business_hours, :budget, :payment_method, :seat, :staff, :parking, :promotion, :introduction, :shop_image, :genre_id])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    shop_mypage_path
  end

  def after_update_path_for(resource)
    shop_mypage_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/shop/reservation_histories_controller.rb
class Shop::ReservationHistoriesController < ApplicationController
  before_action :authenticate_shop!, except: [:review]
  require 'csv'

  def review
    @shop = Shop.find(params[:id])
    @menus = @shop.menus.all
    @reservation_histories = ReservationHistory.where(menu_id: @menus)
    @history_comments = HistoryComment.where(reservation_history_id: @reservation_histories).
      reverse_order
  end

  def index
    @menus = Menu.where(shop_id: current_shop)
    @reservation_histories = ReservationHistory.where(menu_id: @menus).
      includes(:reserve).
      order("reserves.reservation DESC")
    @history_comments = HistoryComment.where(reservation_history_id: @reservation_histories).
      reverse_order
    respond_to do |format|
      format.html
      format.csv do |csv|
        send_reservation_histories_csv(@reservation_histories)
      end
    end
  end

  def update
    @menus = Menu.where(shop_id: current_shop)
    @reservation_histories = ReservationHistory.where(menu_id: @menus)
    @reservation_history = @reservation_histories.find_by(id: params[:id])
    if @reservation_history.present?
      @reservation_history.update(reservation_history_params)
      redirect_to request.referer
    else
      redirect_to shops_histories_path
    end
  end

  private

  def reservation_history_params
    params.require(:reservation_history).permit(:status)
  end

  def send_reservation_histories_csv(reservation_histories)
    csv_data = CSV.generate do |csv|
      column_names = %w(予約日時 予約者 予約メニュー メニュー金額 来店状況)
      csv << column_names

      reservation_histories.each do |history|
        column_values = [
          history.reserve.reservation.to_s(:datetime_jp),
          history.reserve.customer.full_name,
          history.menu.name,
          history.menu.price.to_s(:delimited),
          history.status_i18n,
        ]
        csv << column_values
      end
    end
    send_data(csv_data, filename: "予約状況.csv")
  end
end

app/controllers/shop/sessions_controller.rb
# frozen_string_literal: true

class Shop::SessionsController < Devise::SessionsController
  before_action :reject_inactive_shop, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_in_path_for(resource)
    shop_mypage_path
  end

  def after_sign_out_path_for(resource)
    new_shop_session_path
  end

  def reject_inactive_shop
    @shop = Shop.find_by(email: params[:shop][:email])
    if @shop
      if @shop.valid_password?(params[:shop][:password]) && !@shop.is_active
        flash[:danger] = 'お客様は退会済みです。申し訳ございませんが、別のメールアドレスをお使いください。'
        redirect_to new_shop_session_path
      end
    end
  end
end

app/controllers/shop/unlocks_controller.rb
# frozen_string_literal: true

class Shop::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/shop/bookmarks_helper.rb
module Shop::BookmarksHelper
end

app/helpers/shop/favorites_helper.rb
module Shop::FavoritesHelper
end

app/helpers/shop/menus_helper.rb
module Shop::MenusHelper
end

app/helpers/shop/post_comments_helper.rb
module Shop::PostCommentsHelper
end

app/views/shop/posts/_comment.html.erb
<% post_comments.each do |post_comment| %>
	<tr>
		<td style="white-space: pre-wrap;"><%= post_comment.body %></td>
		<td><%= post_comment.customer.full_name %></td>
		<td><%= post_comment.created_at.to_s(:datetime_jp)  %></td>
		<% if customer_signed_in? %>
			<td>
				<% if current_customer == post_comment.customer %>
				  <%= link_to '削除', shop_post_post_comment_path(shop.id, post.id, post_comment), class: 'btn-sm btn-danger', method: :delete, remote: true %>
				<% end %>
			</td>
		<% end %>
	</tr>
<% end %>

app/views/shop/posts/_form.html.erb
<%= form_with model:[post_comment], url: shop_post_post_comments_path(shop.id, post.id), remote: true do |f| %>
<% if post_comment.errors.any? %>
<% end %>
	<div class="col-md-8 col-md-offset-2 comment-form">
		<%= f.text_area :body, id: "comment_body" %><br>
    <p id="counter">(0文字/140文字中)
		<% if post_comment.errors.include?(:body) %>
      <p style="color: red;"><%= post_comment.errors.full_messages_for(:body).first %>
    <% end %>
	</div>
	<div class="col-md-offset-10">
		<% if customer_signed_in? %>
			<%= f.submit '送信', class: "btn btn-primary btn-lg" %>
		<% else %>
			<%= link_to '送信', new_customer_session_path, class: "btn btn-primary btn-lg" %>
		<% end %>
	</div>
<% end %>

<script>
$(function(){
  $("#comment_body").on('keyup', function() {
   let count = String($(this).val().length);
   $("#counter").text("(" + count + "文字/140文字中)");
  });
});
</script>

app/views/shop/posts/all_index.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<h2>最近の投稿一覧<span class="sub_title">　　　　<%= paginate @posts %></span>
			<%= link_to 'いいね順', posts_rank_path, class: "btn btn-default nav-btn" %>
			<% if customer_signed_in? %>
				<%= link_to '写真検索へ', new_img_search_path, class: "btn btn-default nav-btn" %>
			<% end %>
		</h2>
		<% @posts.each do |post| %>
			<div class="col-md-4 col-xs-4">
				<div class="posts">
					<%= link_to shop_post_path(post.shop, post) do %>
						<%= attachment_image_tag post, :post_image, format: "jpeg", fallback: "no-image.png", class: "post_default_image" %>
						<div class="mask">
							<div class="caption">
								<% if post.favorited_by?(current_customer) %>
									<span class="glyphicon glyphicon-heart"> <%= post.favorites.count%>　</span>
								<% else %>
									<span class="glyphicon glyphicon-heart-empty"> <%= post.favorites.count %>　</span>
								<% end %>
								<span class="glyphicon glyphicon-envelope"> <%= post.post_comments.count %></span>
							</div>
						</div>
					<% end %>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/shop/posts/index.html.erb
<div class="row">
	<div class="col-md-10 col-md-offset-2">
		<h2>投稿一覧
			<span class="sub_title">　　　<%= paginate @posts %>
				<%= link_to new_shop_post_path do %>
					<button class="col-md-offset-6" type="button">＋</button>
				<% end %>
			</span>
		</h2>
	</div>
</div>
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<table class="table">
			<tbody>
				<% @posts.each do |post| %>
					<tr>
						<td><%= attachment_image_tag post, :post_image, format: "jpeg", fallback: "no-image.png", class: "post_index_image" %></td>
						<td>
							<div class="row-2" style="white-space: pre-wrap;"><%= post.body %></div><br>
							<span><%= post.created_at.to_s(:datetime_jp) %>　　</span>
							<span class="glyphicon glyphicon-heart-empty"> <%= post.favorites.count %>　</span>
							<span class="glyphicon glyphicon-envelope"> <%= post.post_comments.count %></span><br>
							<% post.tags.each do |tag| %>
							  <span><%= tag.name %></span>
							<% end %>
						</td>
						<td><%= link_to "編集", edit_shop_post_path(current_shop, post), class: "btn btn-success ml2" %></td>
						<td><%= link_to "削除", shop_post_path(current_shop, post), method: :delete, "data-confirm" => "削除してもよろしいでしょうか？", class: "btn btn-danger"  %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/shop/posts/list.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<h2>
			<%= link_to shop_path(@shop) do %>
				<%= @shop.name %>
			<% end %>
			<span class="sub_title">　の投稿一覧　　　<%= paginate @posts %></span>
			<% if customer_signed_in? %>
				<%= link_to '写真検索へ', new_img_search_path, class: "btn btn-default nav-btn" %>
			<% end %>
		</h2>
		<% @posts.each do |post| %>
			<div class="col-md-4 col-xs-4">
				<div class="posts">
					<%= link_to shop_post_path(@shop, post) do %>
						<%= attachment_image_tag post, :post_image, format: "jpeg", fallback: "no-image.png", class: "post_default_image" %>
						<div class="mask">
							<div class="caption">
								<% if post.favorited_by?(current_customer) %>
									<span class="glyphicon glyphicon-heart"> <%= post.favorites.count%>　</span>
								<% else %>
									<span class="glyphicon glyphicon-heart-empty"> <%= post.favorites.count %>　</span>
								<% end %>
								<span class="glyphicon glyphicon-envelope"> <%= post.post_comments.count %></span>
							</div>
						</div>
					<% end %>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/shop/posts/rank.html.erb
<style>
nav.pagination {
  display: none;
}
</style>
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<h2>いいねランキング<span class="sub_title"></span>
			<%= link_to '投稿順', posts_all_path, class: "btn btn-default nav-btn" %>
			<% if customer_signed_in? %>
				<%= link_to '写真検索へ', new_img_search_path, class: "btn btn-default nav-btn" %>
			<% end %>
		</h2>
		<div class="scroll-list jscroll">
			<% @posts.each do |post| %>
				<div class="col-md-4 col-xs-4">
					<div class="posts">
						<%= link_to shop_post_path(post.shop, post) do %>
							<%= attachment_image_tag post, :post_image, format: "jpeg", fallback: "no-image.png", class: "post_default_image" %>
							<div class="mask">
								<div class="caption">
									<% if post.favorited_by?(current_customer) %>
										<span class="glyphicon glyphicon-heart"> <%= post.favorites.count%>　</span>
									<% else %>
										<span class="glyphicon glyphicon-heart-empty"> <%= post.favorites.count %>　</span>
									<% end %>
									<span class="glyphicon glyphicon-envelope"> <%= post.post_comments.count %></span>
								</div>
							</div>
						<% end %>
					</div>
				</div>
			<% end %>
			<%= paginate @posts %>
		</div>
	</div>
</div>

app/views/shop/posts/show.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-2">
		<h2>
			<%= link_to shop_path(@shop) do %>
				<%= @shop.name %>
			<% end %>
			<span class="sub_title">　の投稿　　　　　　　</span>
			<%= link_to shop_posts_list_path(@shop), class: "btn btn-default nav-btn" do %>
				<%= @shop.name %>の投稿一覧
			<% end %>
		</h2>
		<table class="table">
			<tbody>
				<tr>
					<td>
		        <%= attachment_image_tag @post, :post_image, format: "jpeg", fallback: "no-image.png", class: "post_default_image" %>
		      </td>
					<td>
						<span style="white-space: pre-wrap;"><%= @post.body %></span><br><br><br>
						<%= @post.created_at.to_s(:datetime_jp) %><br><br>
						<% if customer_signed_in? %>
							<div>
								<span id="show_like">
									<%= render partial: 'shop/favorites/form', locals: { shop: @shop, post: @post } %>
								</span>　　
								<span id="comment_count" class="glyphicon glyphicon-envelope"> <%= @post.post_comments.count %></span>
							</div>
						<% else %>
							<%= link_to new_customer_session_path do %>
								<div class="row">
									<div class="col-md-offset-2">
										<span class="glyphicon glyphicon-heart-empty"> <%= @post.favorites.count %>　　</span>
										<span class="glyphicon glyphicon-envelope"> <%= @post.post_comments.count %></span>
									</div>
								</div>
							<% end %>
						<% end %>
					</td>
				</tr>
			</tbody>
		</table>
	</div>
</div>
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<h2>コメント一覧</h2>
		<table class="table table-bordered">
			<thead>
				<tr>
					<th>コメント内容</th>
					<th>投稿者</th>
					<th>投稿日時</th>
					<% if customer_signed_in? %>
						<th></th>
					<% end %>
				</tr>
			</thead>
			<tbody id="comment">
				<%= render partial: 'shop/posts/comment',locals: { shop: @shop, post: @post, post_comments: @post.post_comments } %>
			</tbody>
		</table>
	</div>
</div>
<div class="row" id="comment_form">
	<%= render partial: 'shop/posts/form',locals: { shop: @shop, post: @post, post_comment: @post_comment } %>
</div>