config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
  }
  devise_for :shops, controllers: {
    sessions: 'shop/sessions',
    registrations: 'shop/registrations',
    passwords: 'shop/passwords',
  }
  devise_for :customers, controllers: {
    sessions: 'public/sessions',
    registrations: 'public/registrations',
    passwords: 'public/passwords',
  }
  scope module: :admin do
    resources :genres, only: [:index, :create, :edit, :update]
  end

  scope module: :public do
    root 'homes#top'
    get 'about', to: 'homes#about'
    get 'customers/mypage' => 'customers#mypage', as: 'mypage'
    get 'customers/information/edit' => 'customers#edit', as: 'edit_information'
    patch 'customers/information' => 'customers#update', as: 'update_information'
    put 'customers/information' => 'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'confirm_unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw_customer'
    put 'customers/withdraw' => 'customers#withdraw'
    get 'reserves/confirm', to: 'reserves#confirm', as: 'reserve_confirm'
    post 'reserves/confirm', to: 'reserves#confirm', as: 'reserves_confirm_post'
    post 'reserves/create', to: 'reserves#create', as: 'reserves_create'
    get 'reserves/done', to: 'reserves#done', as: 'reserves_done'
    get 'customers/:customer_id/talk_rooms/:id' => 'talks#show', as: 'customers_talk'
    get 'customers/talks' => 'talks#index', as: 'customers_talks'
    get 'search', to: 'searchs#search', as: 'search'
    get 'map_search', to: 'searchs#map_search', as: 'map_search'
    get 'customers/follows' => 'relationships#follow', as: 'follow'
    get 'customers/bookmarks' => 'bookmarks#index', as: 'bookmarks'
    get 'customers/reserve' => 'reserves#new', as: 'reserve'
    get 'customers/rank' => 'customers#rank', as: 'customers_rank'
    get 'imgsearch', to: 'img_searchs#search', as: 'img_search'

    resources :customers, only: [:index, :show] do
      resources :talks, only: [:create]
      resource :relationships, only: [:create, :destroy]
      resources :reservation_menus, only: [:create]
      resources :reservation_histories, only: [:index] do
        resources :history_comments, only: [:create, :destroy]
      end
    end
    resources :reservation_menus, only: [:index]
    resources :talks, only: [:create]
    resources :img_searchs, only: [:create, :new]
    delete 'img_searchs/:id' => 'img_searchs#destroy', as: 'img_search_destroy'
  end

  scope module: :shop do
    get 'shops/mypage' => 'shops#mypage', as: 'shop_mypage'
    get 'shops/information/edit' => 'shops#edit', as: 'edit_shop_information'
    patch 'shops/information' => 'shops#update', as: 'update_shop_information'
    put 'shops/information' => 'shops#update'
    get 'shops/unsubscribe' => 'shops#unsubscribe', as: 'confirm_shop_unsubscribe'
    patch 'shops/withdraw' => 'shops#withdraw', as: 'withdraw_shop'
    put 'shops/withdraw' => 'shops#withdraw'
    get 'shops/:id/menulist' => 'shops#menu', as: 'shop_menu_list'
    get 'posts/all' => 'posts#all_index'
    get 'posts/rank' => 'posts#rank'
    get 'shops/:id/postlist' => 'posts#list', as: 'shop_posts_list'
    get 'shops/map' => 'shops#map', as: 'shops_map'
    get 'talk_rooms/:id/:shop_id/:customer_id' => 'talks#show', as: 'shops_talk'
    get 'shops/talks' => 'talks#index', as: 'shops_talks'
    get 'shops/reservation_histories' => 'reservation_histories#index', as: 'shops_histories'
    patch 'shops/reservation_histories/:id' => 'reservation_histories#update', as: 'update_history'
    get '/genres/:genre_id' => 'shops#search', as: 'shops_search'
    get '/mapgenres/:genre_id' => 'shops#map_search', as: 'shops_map_search'
    get 'shops/:id/review' => 'reservation_histories#review', as: 'shop_review'

    resources :shops, only: [:index, :show] do
      resources :menus, except: [:show]
      resource :bookmarks, only: [:create, :destroy]
      resources :talks, only: [:create]
      resources :posts do
        resources :post_comments, only: [:create, :destroy]
        resource :favorites, only: [:create, :destroy]
      end
    end
  end
end

app/views/layouts/_header.erb
<header class="main-header navbar-fixed-top" data-turbolinks="false">
  <div class="container navbar-fixed-top nav-head">
    <div class="row">
      <div class="main-header">
        <div class="nav navbar-nav navbar-left">
          <%= link_to 'Nailsite', root_path, class: "logo" %>
        </div>
        <nav>
          <ul id="reveal" class="nav navbar-nav navbar-right col-xs-2 col-xs-offset-10">
            <li role="presentation" class="dropdown">
              <a class="dropdown-toggle btn btn-default nav-btn" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
                メニュー <span class="caret"></span>
              </a>
              <ul id="dropdown-menu" class="dropdown-menu" role="menu">
                <li role="presentation"><%= link_to '使い方', about_path %></li>
                <li role="presentation"><%= link_to '店舗一覧', shops_path %></li>
                <li role="presentation"><%= link_to '投稿一覧', posts_all_path %></li>
                <li role="presentation"><%= link_to '会員一覧', customers_path %></li>
                <li role="presentation"><%= link_to '新規登録', new_customer_registration_path %></li>
                <li role="presentation"><%= link_to 'ログイン', new_customer_session_path %></li>
              </ul>
            </li>
          </ul>
          <ul id="erase" class="nav navbar-nav navbar-right">
            <li><%= link_to '使い方', about_path, class: "btn btn-default nav-btn" %></li>
            <li><%= link_to '店舗一覧', shops_path, class: "btn btn-default nav-btn" %></li>
            <li><%= link_to '投稿一覧', posts_all_path, class: "btn btn-default nav-btn" %></li>
            <li><%= link_to '会員一覧', customers_path, class: "btn btn-default nav-btn" %></li>
            <li><%= link_to '新規登録', new_customer_registration_path, class: "btn btn-default nav-btn" %></li>
            <li><%= link_to 'ログイン', new_customer_session_path, class: "btn btn-default nav-btn" %></li>
          </ul>
        </nav>
      </div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nailsite</title>
    <%= include_gon %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
  </head>
  <body>
    <% if shop_signed_in? %>

      <header class="shop-header navbar-fixed-top" data-turbolinks="false">
        <div class="container navbar-fixed-top nav-head">
          <div class="row">
            <div class="nav navbar-nav navbar-left">
              <%= link_to 'Nailsite', root_path, class: "logo" %>
              <span>　　　ようこそ、<%= current_shop.name %>様!</span>
            </div>
            <nav>
              <ul id="reveal" class="nav navbar-nav navbar-right col-xs-2 col-xs-offset-10">
                <li role="presentation" class="dropdown">
                  <a class="dropdown-toggle btn btn-default nav-btn" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
                    MENU <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu" role="menu">
                    <li role="presentation"><%= link_to 'マイページ', shop_mypage_path %></li>
                    <li role="presentation"><%= link_to '予約一覧', shops_histories_path, data: {"turbolinks"=>false} %></li>
                    <li role="presentation"><%= link_to '連絡一覧', shops_talks_path %></li>
                    <li role="presentation"><%= link_to 'メニュー', shop_menus_path(current_shop) %></li>
                    <li role="presentation"><%= link_to '投稿一覧', shop_posts_path(current_shop) %></li>
                    <li role="presentation"><%= link_to '会員一覧', customers_rank_path %></li>
                    <li role="presentation"><%= link_to 'ログアウト', destroy_shop_session_path, method: :delete %></li>
                  </ul>
                </li>
              </ul>
              <ul id="erase" class="nav navbar-nav navbar-right">
                <li><%= link_to 'マイページ', shop_mypage_path, class: "btn btn-default nav-btn" %></li>
                <li><%= link_to '予約一覧', shops_histories_path, data: {"turbolinks"=>false}, class: "btn btn-default nav-btn" %></li>
                <li><%= link_to '連絡一覧', shops_talks_path, class: "btn btn-default nav-btn" %></li>
                <li><%= link_to 'メニュー', shop_menus_path(current_shop), class: "btn btn-default nav-btn" %></li>
                <li><%= link_to '投稿一覧', shop_posts_path(current_shop), class: "btn btn-default nav-btn" %></li>
                <li><%= link_to '会員一覧', customers_rank_path, class: "btn btn-default nav-btn" %></li>
                <li><%= link_to 'ログアウト', destroy_shop_session_path, method: :delete, class: "btn btn-default nav-btn" %></li>
              </ul>
            </nav>
          </div>
        </div>
      </header>
      <div class="container main_body">
        <main data-turbolinks="false"><%= yield %></main>
      </div>
    
    <% elsif customer_signed_in? %>
      <header class="customer-header navbar-fixed-top" data-turbolinks="false">
        <div class="container navbar-fixed-top nav-head">
          <div class="row">
            <div class="nav navbar-nav navbar-left">
              <%= link_to 'Nailsite', root_path, class: "logo" %>
              <span>　　　ようこそ、<%= current_customer.full_name %>さん!</span>
            </div>
            <nav>
              <ul id="reveal" class="nav navbar-nav navbar-right col-xs-2 col-xs-offset-10">
                <li role="presentation" class="dropdown">
                  <a class="dropdown-toggle btn btn-default nav-btn" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
                    MENU <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu" role="menu">
                    <li role="presentation"><%= link_to 'マイページ', mypage_path %></li>
                    <li role="presentation"><%= link_to '店舗一覧', shops_path %></li>
                    <li role="presentation"><%= link_to '投稿一覧', posts_all_path %></li>
                    <li role="presentation"><%= link_to '会員一覧', customers_path %></li>
                    <li role="presentation"><%= link_to 'ログアウト', destroy_customer_session_path, method: :delete %></li>
                  </ul>
                </li>
              </ul>
              <ul id="erase" class="nav navbar-nav navbar-right">
                <li><%= link_to 'マイページ', mypage_path, class: "btn btn-default nav-btn" %></li>
                <li><%= link_to '店舗一覧', shops_path, class: "btn btn-default nav-btn" %></li>
                <li><%= link_to '投稿一覧', posts_all_path, class: "btn btn-default nav-btn" %></li>
                <li><%= link_to '会員一覧', customers_path, class: "btn btn-default nav-btn" %></li>
                <li><%= link_to 'ログアウト', destroy_customer_session_path, method: :delete, class: "btn btn-default nav-btn" %></li>
              </ul>
            </nav>
          </div>
        </div>
      </header>
      <div class="container main_body">
        <main data-turbolinks="false"><%= yield %></main>
      </div>
    <% elsif current_page?(root_path) %>
      <header class="top-header navbar-fixed-top" data-turbolinks="false">
        <div class="main-visual-content logo-link">
          <p class="main-visual-text">
            <span class="root_logo">Nailsite</span><br>
            Nailsiteへ、ようこそ！<br><br>
            会員でない方も閲覧はできますが、<br>
            ご予約には会員登録が必要になります
          </p>
        </div>
        <div class="container navbar-fixed-top nav-head">
          <div class="row">
            <nav>
              <ul id="reveal" class="nav navbar-nav navbar-right col-xs-2 col-xs-offset-10">
                <li role="presentation" class="dropdown">
                  <a class="dropdown-toggle btn btn-default nav-btn" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
                    メニュー <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu" role="menu">
                    <li role="presentation"><%= link_to '使い方', about_path %></li>
                    <li role="presentation"><%= link_to '店舗一覧', shops_path %></li>
                    <li role="presentation"><%= link_to '投稿一覧', posts_all_path %></li>
                    <li role="presentation"><%= link_to '会員一覧', customers_path %></li>
                    <li role="presentation"><%= link_to '新規登録', new_customer_registration_path %></li>
                    <li role="presentation"><%= link_to 'ログイン', new_customer_session_path %></li>
                  </ul>
                </li>
              </ul>
              <ul id="erase" class="nav navbar-nav navbar-right">
                <li><%= link_to '使い方', about_path, class: "btn btn-default nav-btn" %></li>
                <li><%= link_to '店舗一覧', shops_path, class: "btn btn-default nav-btn" %></li>
                <li><%= link_to '投稿一覧', posts_all_path, class: "btn btn-default nav-btn" %></li>
                <li><%= link_to '会員一覧', customers_path, class: "btn btn-default nav-btn" %></li>
                <li><%= link_to '新規登録', new_customer_registration_path, class: "btn btn-default nav-btn" %></li>
                <li><%= link_to 'ログイン', new_customer_session_path, class: "btn btn-default nav-btn" %></li>
              </ul>
            </nav>
          </div>
          <div class="row">
            <div class="col-md-offset-6 col-xs-offset-5 search_box">
              <%= form_tag(search_path, method: :get) do %>
                <%= text_field_tag 'search[content]', '', class: 'search_form', placeholder: "店名/場所から探す　【例：nailsalon、梅田】"%>
                <%= submit_tag '検索', class: "btn btn-default search_btn" %>
              <% end %>
            </div>
          </div>
        </div>
      </header>
      <div class="container top_body">
        <main data-turbolinks="false"><%= yield %></main>
      </div>
    <% elsif current_page?(about_path)%>
      <%= render 'layouts/header' %>
      <div class="main_body">
        <main data-turbolinks="false"><%= yield %></main>
      </div>
    <% else %>
      <%= render 'layouts/header' %>
      <div class="container main_body">
        <main data-turbolinks="false"><%= yield %></main>
      </div>
    <% end %>
    <span id="back">
      <a href=""><%= image_tag asset_path('arrow.jpg'), data: {"turbolinks"=>false}, class: "arrow" %></a>
    </span>
    <div class="container">
      <footer>Copyright © Nailsite. All Rights Reserved.</footer>
    </div>

   

  </body>
</html>